// src/pages/Payroll.jsx
import { useState, useEffect, useCallback } from 'react'
import { api } from '../api/client'
import { useAuthStore } from '../store/authStore'
import { useToast } from '../hooks/useToast'
import { SkeletonTable } from '../components/Skeleton'

function fmt(n) { return '₹' + (Number(n) || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 }) }
function fmtH(h) {
  if (!h) return '—'
  const hrs  = Math.floor(h)
  const mins = Math.round((h - hrs) * 60)
  return mins > 0 ? `${hrs}h ${mins}m` : `${hrs}h`
}

export default function Payroll() {
  const rid   = useAuthStore(s => s.restaurantId)
  const toast = useToast()
  const [staff,    setStaff]    = useState([])
  const [loading,  setLoading]  = useState(true)
  const [month,    setMonth]    = useState(new Date().toISOString().slice(0, 7))
  const [selected, setSelected] = useState(null)
  const [paying,   setPaying]   = useState(null)

  // ── Load payroll summary from backend ────────────────────────────
  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await api.get(`/payroll/summary?restaurantId=${rid}&month=${month}`)
      setStaff(res?.staffList || [])
    } catch (_) {
      setStaff([])
    } finally { setLoading(false) }
  }, [rid, month])

  useEffect(() => { load() }, [month])

  // ── Mark as paid ─────────────────────────────────────────────────
  async function markPaid(s) {
    setPaying(s.staffId)
    try {
      await api.post('/payroll/pay', {
        staffId: s.staffId, month, amount: s.netPayable, restaurantId: rid,
      })
      toast.success(`✅ ${s.staffName} — ${fmt(s.netPayable)} marked as paid!`)
      load()
    } catch (_) {
      toast.error('Mark paid failed')
    } finally { setPaying(null) }
  }

  // ── Download salary slip ──────────────────────────────────────────
  function downloadSlip(s) {
    const regularPay = s.grossSalary - (s.overtimePay || 0)
    const html = `
      <html><head><style>
        body{font-family:Arial,sans-serif;padding:40px;max-width:600px;margin:auto}
        .header{background:#6366f1;color:white;padding:20px;border-radius:8px;margin-bottom:24px;text-align:center}
        .row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee;font-size:14px}
        .section{font-size:11px;color:#999;text-transform:uppercase;margin:16px 0 4px}
        .total{font-weight:bold;font-size:16px;color:#10b981}
        .ot{color:#f59e0b}
        .deduct{color:#ef4444}
      </style></head><body>
        <div class="header">
          <h2 style="margin:0 0 4px">💼 Salary Slip</h2>
          <div>${month}</div>
        </div>
        <div class="row"><span>Employee</span><strong>${s.staffName}</strong></div>
        <div class="row"><span>Role</span><span>${[...(s.roles || [])].join(', ')}</span></div>
        <div class="row"><span>Salary Type</span><span>${s.salaryType}</span></div>
        <div class="row"><span>Attendance</span><span>${s.attendanceDays}/${s.totalDays} days</span></div>
        ${s.salaryType === 'HOURS' ? `
        <div class="section">Hours Breakdown</div>
        <div class="row"><span>Total Hours</span><span>${fmtH(s.monthlyHours)}</span></div>
        ${s.overtimeEnabled && s.overtimeHours > 0 ? `
        <div class="row"><span>Regular Hours</span><span>${fmtH(s.regularHours)}</span></div>
        <div class="row ot"><span>Overtime Hours</span><span>${fmtH(s.overtimeHours)}</span></div>
        ` : ''}
        ` : ''}
        <div class="section">Earnings</div>
        <div class="row"><span>Regular Pay</span><span>${fmt(regularPay)}</span></div>
        ${s.overtimePay > 0 ? `<div class="row ot"><span>Overtime Pay</span><span>+ ${fmt(s.overtimePay)}</span></div>` : ''}
        <div class="row"><span>Gross Salary</span><strong>${fmt(s.grossSalary)}</strong></div>
        <div class="section">Deductions</div>
        <div class="row deduct"><span>Advance</span><span>- ${fmt(s.pendingAdvance || 0)}</span></div>
        <div class="row deduct"><span>Loan</span><span>- ${fmt(s.loanBalance || 0)}</span></div>
        <div class="row total" style="margin-top:12px;padding-top:12px;border-top:2px solid #333">
          <span>Net Payable</span><span>${fmt(s.netPayable)}</span>
        </div>
        <p style="text-align:center;color:#999;font-size:12px;margin-top:32px">
          Generated by HarmoneyEats • ${new Date().toLocaleDateString()}
        </p>
      </body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `salary-slip-${s.staffName.replace(' ', '-')}-${month}.html`
    a.click()
    URL.revokeObjectURL(url)
    toast.success(`📄 Salary slip downloaded: ${s.staffName}`)
  }

  // ── Totals ────────────────────────────────────────────────────────
  const totals = staff.reduce((acc, s) => ({
    gross:   acc.gross   + (s.grossSalary    || 0),
    net:     acc.net     + (s.netPayable     || 0),
    advance: acc.advance + (s.pendingAdvance || 0),
    loan:    acc.loan    + (s.loanBalance    || 0),
    otPay:   acc.otPay   + (s.overtimePay   || 0),
  }), { gross: 0, net: 0, advance: 0, loan: 0, otPay: 0 })

  const StatCard = ({ label, value, color = 'var(--text)' }) => (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 12, padding: '1.25rem' }}>
      <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 8 }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 700, color }}>{value}</div>
    </div>
  )

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 700 }}>💼 Payroll</h1>
          <p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>
            Attendance-linked salary with overtime breakdown
          </p>
        </div>
        <input type="month" value={month} onChange={e => setMonth(e.target.value)} style={{
          padding: '8px 12px', borderRadius: 8, border: '1px solid var(--border)',
          background: 'var(--bg-page)', color: 'var(--text)', fontSize: 13,
        }} />
      </div>

      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 12, marginBottom: '1.5rem' }}>
        <StatCard label="💰 Total Gross"   value={fmt(totals.gross)}   color="#10b981" />
        <StatCard label="🏦 Net Payable"   value={fmt(totals.net)}     color="#6366f1" />
        <StatCard label="📤 Total Advance" value={fmt(totals.advance)} color="#f59e0b" />
        <StatCard label="🔄 Loan Balance"  value={fmt(totals.loan)}    color="#ef4444" />
        {totals.otPay > 0 && (
          <StatCard label="⏰ OT Pay"      value={fmt(totals.otPay)}   color="#f59e0b" />
        )}
        <StatCard label="👥 Staff"         value={staff.length} />
      </div>

      {/* Table */}
      <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden' }}>
        {loading ? <SkeletonTable rows={4} cols={8} /> : staff.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '48px 0', color: 'var(--text-muted)', fontSize: 14 }}>
            <div style={{ fontSize: 32, marginBottom: 8 }}>💼</div>
            <div>Is month ke liye koi payroll data nahi hai</div>
            <div style={{ fontSize: 12, marginTop: 4 }}>Staff attendance aur salary settings check karo</div>
          </div>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border)' }}>
                {['Staff', 'Attendance', 'Hours / OT Breakdown', 'Regular Pay', 'OT Pay', 'Gross', 'Deductions', 'Net', 'Actions'].map(h => (
                  <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontSize: 11, color: 'var(--text-muted)', fontWeight: 600 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {staff.map((s, i) => {
                const attPct      = s.totalDays > 0 ? Math.round((s.attendanceDays / s.totalDays) * 100) : 0
                const regularPay  = s.grossSalary - (s.overtimePay || 0)
                const hasOT       = s.overtimeEnabled && s.overtimeHours > 0
                return (
                  <tr key={s.staffId || i} style={{ borderBottom: '1px solid var(--border)' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-page)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>

                    {/* Staff */}
                    <td style={{ padding: '12px 14px' }}>
                      <div style={{ fontWeight: 600, fontSize: 13 }}>{s.staffName}</div>
                      <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 2 }}>
                        {[...(s.roles || [])].join(', ')} · {s.salaryType}
                      </div>
                    </td>

                    {/* Attendance */}
                    <td style={{ padding: '12px 14px' }}>
                      <div style={{ fontSize: 12, marginBottom: 4, color: attPct < 80 ? '#ef4444' : attPct < 95 ? '#f59e0b' : '#10b981' }}>
                        {s.attendanceDays}/{s.totalDays} days ({attPct}%)
                      </div>
                      <div style={{ height: 4, background: 'var(--border)', borderRadius: 2, overflow: 'hidden', width: 80 }}>
                        <div style={{ height: '100%', width: `${attPct}%`, background: attPct < 80 ? '#ef4444' : attPct < 95 ? '#f59e0b' : '#10b981', borderRadius: 2 }} />
                      </div>
                    </td>

                    {/* Hours / OT Breakdown */}
                    <td style={{ padding: '12px 14px', minWidth: 160 }}>
                      {s.salaryType === 'HOURS' ? (
                        <div>
                          <div style={{ fontSize: 12, marginBottom: hasOT ? 4 : 0 }}>
                            Total: <strong>{fmtH(s.monthlyHours)}</strong>
                          </div>
                          {hasOT ? (
                            <>
                              <div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: '#10b981' }}>
                                <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#10b981', display: 'inline-block' }} />
                                Regular: {fmtH(s.regularHours)}
                              </div>
                              <div style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: '#f59e0b', marginTop: 2 }}>
                                <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#f59e0b', display: 'inline-block' }} />
                                OT: {fmtH(s.overtimeHours)}
                              </div>
                            </>
                          ) : s.overtimeEnabled ? (
                            <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>No overtime this month</div>
                          ) : null}
                        </div>
                      ) : (
                        <span style={{ color: 'var(--text-muted)', fontSize: 12 }}>—</span>
                      )}
                    </td>

                    {/* Regular Pay */}
                    <td style={{ padding: '12px 14px', fontSize: 13 }}>
                      {fmt(regularPay)}
                    </td>

                    {/* OT Pay */}
                    <td style={{ padding: '12px 14px', fontSize: 13 }}>
                      {s.overtimePay > 0 ? (
                        <span style={{ color: '#f59e0b', fontWeight: 600 }}>+{fmt(s.overtimePay)}</span>
                      ) : (
                        <span style={{ color: 'var(--text-muted)' }}>—</span>
                      )}
                    </td>

                    {/* Gross */}
                    <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 600 }}>
                      {fmt(s.grossSalary)}
                    </td>

                    {/* Deductions */}
                    <td style={{ padding: '12px 14px', fontSize: 12 }}>
                      {(s.pendingAdvance || s.loanBalance) ? (
                        <div>
                          {s.pendingAdvance > 0 && <div style={{ color: '#f59e0b' }}>Adv: {fmt(s.pendingAdvance)}</div>}
                          {s.loanBalance   > 0 && <div style={{ color: '#ef4444' }}>Loan: {fmt(s.loanBalance)}</div>}
                        </div>
                      ) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>

                    {/* Net */}
                    <td style={{ padding: '12px 14px', fontSize: 14, fontWeight: 700, color: '#10b981' }}>
                      {fmt(s.netPayable)}
                    </td>

                    {/* Actions */}
                    <td style={{ padding: '12px 14px' }}>
                      <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                        <button onClick={() => setSelected(s)} style={{
                          fontSize: 11, padding: '4px 8px', borderRadius: 6,
                          border: '1px solid var(--border)', background: 'transparent',
                          color: 'var(--text-muted)', cursor: 'pointer',
                        }}>Details</button>
                        <button onClick={() => downloadSlip(s)} style={{
                          fontSize: 11, padding: '4px 8px', borderRadius: 6,
                          border: '1px solid #6366f1', background: 'transparent',
                          color: '#6366f1', cursor: 'pointer',
                        }}>📄 Slip</button>
                        <button onClick={() => markPaid(s)} disabled={paying === s.staffId} style={{
                          fontSize: 11, padding: '4px 8px', borderRadius: 6,
                          border: 'none', background: '#10b981', color: '#fff',
                          cursor: paying === s.staffId ? 'not-allowed' : 'pointer',
                          opacity: paying === s.staffId ? 0.6 : 1,
                        }}>{paying === s.staffId ? '…' : 'Pay'}</button>
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
            <tfoot>
              <tr style={{ background: 'var(--bg-page)', borderTop: '2px solid var(--border)' }}>
                <td colSpan={2} style={{ padding: '12px 14px', fontSize: 13, fontWeight: 700 }}>
                  Total ({staff.length} staff)
                </td>
                <td style={{ padding: '12px 14px', fontSize: 12, color: 'var(--text-muted)' }}>
                  {fmtH(staff.filter(s => s.salaryType === 'HOURS').reduce((a, s) => a + (s.monthlyHours || 0), 0))}
                </td>
                <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 700 }}>
                  {fmt(totals.gross - totals.otPay)}
                </td>
                <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 700, color: '#f59e0b' }}>
                  {totals.otPay > 0 ? fmt(totals.otPay) : '—'}
                </td>
                <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 700 }}>{fmt(totals.gross)}</td>
                <td style={{ padding: '12px 14px', fontSize: 12 }}>
                  <div style={{ color: '#f59e0b' }}>Adv: {fmt(totals.advance)}</div>
                  <div style={{ color: '#ef4444' }}>Loan: {fmt(totals.loan)}</div>
                </td>
                <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 700, color: '#10b981' }}>{fmt(totals.net)}</td>
                <td />
              </tr>
            </tfoot>
          </table>
        )}
      </div>

      {/* Detail side panel */}
      {selected && (
        <div style={{ position: 'fixed', right: 0, top: 0, bottom: 0, width: 340,
          background: 'var(--bg-card)', borderLeft: '1px solid var(--border)',
          padding: '1.5rem', overflowY: 'auto', zIndex: 100, boxShadow: '-4px 0 24px rgba(0,0,0,0.15)' }}>

          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: 16, fontWeight: 700 }}>Payroll Detail</h2>
            <button onClick={() => setSelected(null)} style={{ background: 'none', border: 'none', fontSize: 20, cursor: 'pointer', color: 'var(--text-muted)' }}>✕</button>
          </div>

          <div style={{ fontWeight: 600, fontSize: 15, marginBottom: '1rem' }}>👤 {selected.staffName}</div>

          {/* Info rows */}
          {[
            ['Role',       [...(selected.roles || [])].join(', ')],
            ['Salary Type', selected.salaryType],
            ['Attendance', `${selected.attendanceDays}/${selected.totalDays} days`],
          ].map(([l, v]) => (
            <div key={l} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
              <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{l}</span>
              <span style={{ fontSize: 13, fontWeight: 500 }}>{v}</span>
            </div>
          ))}

          {/* Hours breakdown — HOURS type only */}
          {selected.salaryType === 'HOURS' && (
            <div style={{ margin: '12px 0 4px', padding: '12px', borderRadius: 8, background: 'var(--bg-page)', border: '1px solid var(--border)' }}>
              <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase' }}>
                Hours Breakdown
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                <span>Total Hours</span>
                <strong>{fmtH(selected.monthlyHours)}</strong>
              </div>
              {selected.overtimeEnabled ? (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                    <span style={{ color: '#10b981' }}>● Regular Hours</span>
                    <span style={{ color: '#10b981', fontWeight: 600 }}>{fmtH(selected.regularHours)}</span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
                    <span style={{ color: '#f59e0b' }}>● Overtime Hours</span>
                    <span style={{ color: '#f59e0b', fontWeight: 600 }}>{fmtH(selected.overtimeHours)}</span>
                  </div>
                </>
              ) : (
                <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Overtime disabled for this staff</div>
              )}
            </div>
          )}

          {/* Earnings breakdown */}
          <div style={{ margin: '12px 0 4px', padding: '12px', borderRadius: 8, background: 'var(--bg-page)', border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase' }}>
              Earnings
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
              <span>Regular Pay</span>
              <span>{fmt(selected.grossSalary - (selected.overtimePay || 0))}</span>
            </div>
            {selected.overtimePay > 0 && (
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4, color: '#f59e0b' }}>
                <span>⏰ Overtime Pay</span>
                <span style={{ fontWeight: 600 }}>+{fmt(selected.overtimePay)}</span>
              </div>
            )}
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, fontWeight: 600, borderTop: '1px solid var(--border)', paddingTop: 8, marginTop: 4 }}>
              <span>Gross Salary</span>
              <span>{fmt(selected.grossSalary)}</span>
            </div>
          </div>

          {/* Deductions */}
          <div style={{ margin: '12px 0 4px', padding: '12px', borderRadius: 8, background: 'var(--bg-page)', border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase' }}>
              Deductions
            </div>
            {[
              ['Advance', selected.pendingAdvance || 0, '#f59e0b'],
              ['Loan',    selected.loanBalance    || 0, '#ef4444'],
            ].map(([l, v, c]) => (
              <div key={l} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                <span style={{ color: c }}>- {l}</span>
                <span style={{ color: c, fontWeight: 600 }}>{fmt(v)}</span>
              </div>
            ))}
          </div>

          {/* Net */}
          <div style={{ display: 'flex', justifyContent: 'space-between', padding: '14px 0', fontSize: 16, fontWeight: 700, color: '#10b981', borderTop: '2px solid var(--border)', marginTop: 8 }}>
            <span>Net Payable</span>
            <span>{fmt(selected.netPayable)}</span>
          </div>

          <button onClick={() => downloadSlip(selected)} style={{ width: '100%', marginTop: '1rem', padding: '10px', background: '#6366f1', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
            📄 Download Salary Slip
          </button>
          <button onClick={() => { markPaid(selected); setSelected(null) }} style={{ width: '100%', marginTop: 8, padding: '10px', background: '#10b981', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
            💳 Mark as Paid
          </button>
        </div>
      )}
    </div>
  )
}
